info:
  project: DemoJPA
  description: Demo de prueba para JPA
  version: 0.0.1-SNAPSHOT

server:
  port: 8888
  
spring:
  application:
    name: DemoJPA
  datasource:
    url: jdbc:mysql://localhost:3306/concretepage
    username: root
    password: root
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings : false
        format_sql : true